name: neurithm
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.3.0 
  http: ^1.2.2
  audioplayers: ^6.1.0
  path_provider: ^2.0.11 
  flutter_audio_waveforms: ^1.2.1+8  
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
   - family: Vonique
     fonts:
        - asset: assets/fonts/Vonique 43_D.otf
   - family: Lato
     fonts:
        - asset: assets/fonts/Lato-Thin.ttf
 
