name: neurithm
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.3.0
  http: ^1.2.2
  audioplayers: ^6.1.0
  path_provider: ^2.0.11
  flutter_audio_waveforms: ^1.2.1+8
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.2 # For saving user preferences
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  flutter_rating_bar: ^4.0.0
  csv: ^6.0.0
  file_picker: ^8.3.5
  flutter_dotenv: ^5.2.1
  flutter_blue_plus: ^1.15.0
  permission_handler: ^11.0.1
  local_auth: ^2.1.6
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_localizations:
        sdk: flutter
  flutter_email_sender: ^7.0.0
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: Vonique
      fonts:
        - asset: assets/fonts/Vonique 43_D.otf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
flutter_intl:
  enabled: true
